OUS_FLAG_COUNT = 4
OSU_FLAG_DOT = 1
OSU_FLAG_SLIDER = 2
OSU_FLAG_NEW_COMBO = 4
OSU_FLAG_SPINNER = 8
OSU_OBJECT_FLAGS = [OSU_FLAG_DOT, OSU_FLAG_SLIDER, OSU_FLAG_NEW_COMBO, OSU_FLAG_SPINNER]
OSU_OBJECT_NAMES = ["Dot", "Slider", "New combo", "Spinner"]
LOCAL_FLAG_DOT = 0
LOCAL_FLAG_SLIDER = 1
LOCAL_FLAG_SPINNER = 3
LOCAL_TYPE_FLAGS = [0, 1, 3]
#4 is irrelevant?
